# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170318_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeetupProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_id', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('place_name', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='UserLocation',
        ),
        migrations.AddField(
            model_name='invitee',
            name='meetup_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MeetupProposal'),
        ),
    ]
