# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170319_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetupproposal',
            old_name='date_time',
            new_name='start_time',
        ),
    ]
