# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170324_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCloudMessagingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('address', models.CharField(max_length=255)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
